//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBillingGroup
    {
        public int BillingGroupID { get; set; }
        public string BillingGroupName { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public string DivisionName { get; set; }
        public string BusinessUnit { get; set; }
    }
}
