//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientIncidentalRate
    {
        public int ClientID { get; set; }
        public Nullable<int> NetDayTradeCredit { get; set; }
        public Nullable<decimal> ManualEntry { get; set; }
        public Nullable<decimal> ManualEntryRevenue { get; set; }
        public Nullable<decimal> FollowUp { get; set; }
        public Nullable<decimal> ProductSetup { get; set; }
        public Nullable<decimal> ProductMaintenance { get; set; }
        public Nullable<decimal> LabelSetup { get; set; }
        public Nullable<decimal> LabelPrint { get; set; }
        public Nullable<decimal> Relabel { get; set; }
        public Nullable<decimal> RelabelLabor { get; set; }
        public Nullable<decimal> MsdsCoaPrint { get; set; }
        public Nullable<decimal> CCProcessFee { get; set; }
        public Nullable<decimal> RushShipment { get; set; }
        public Nullable<decimal> EmptyContainer { get; set; }
        public Nullable<decimal> EmptyPail { get; set; }
        public Nullable<decimal> InactiveStockStorage { get; set; }
        public Nullable<decimal> ITProjectSupport { get; set; }
    }
}
