//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCeaseShipOffSet
    {
        public int CeaseShipOffsetID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> OffsetDays { get; set; }
    }
}
