//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCAS
    {
        public int CASID { get; set; }
        public Nullable<int> ProductDetailID { get; set; }
        public string CasNumber { get; set; }
        public string ChemicalName { get; set; }
        public string Percentage { get; set; }
        public Nullable<bool> RestrictedQty { get; set; }
        public Nullable<decimal> RestrictedAmount { get; set; }
        public Nullable<bool> PackOnReceipt { get; set; }
        public Nullable<bool> ReportableQty { get; set; }
        public Nullable<decimal> ReportableAmount { get; set; }
        public Nullable<bool> LessThan { get; set; }
        public Nullable<bool> ExcludeFromLabel { get; set; }
        public string Company_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string ProdCode_MDB { get; set; }
    }
}
