//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCarrier
    {
        public int CarrierID { get; set; }
        public Nullable<int> MasterCarrierID { get; set; }
        public string CarrierName { get; set; }
        public Nullable<int> ServiceLevel { get; set; }
        public string CMCLocation { get; set; }
        public byte[] TS { get; set; }
    }
}
