//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientInvoiceTrans
    {
        public int InvoiceTransID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> PONumber { get; set; }
        public Nullable<int> NetDayTradeCredit { get; set; }
        public Nullable<int> BillClientID { get; set; }
        public string BillClientName { get; set; }
        public string BillClientAttention { get; set; }
        public string BillClientAddress1 { get; set; }
        public string BillClientAddress2 { get; set; }
        public string BillClientCity { get; set; }
        public string BillClientState { get; set; }
        public string BillClientZip { get; set; }
        public string BillClientCountry { get; set; }
        public string RemitToCompany { get; set; }
        public string RemitToAtention { get; set; }
        public string RemitToAddress1 { get; set; }
        public string RemitToAddress2 { get; set; }
        public string RemitToCity { get; set; }
        public string RemitToState { get; set; }
        public string RemitToZip { get; set; }
        public string RemitToCountry { get; set; }
        public Nullable<int> TotalSamples { get; set; }
        public Nullable<decimal> TotalSampleCost { get; set; }
        public Nullable<decimal> TotalFreight { get; set; }
        public Nullable<decimal> TotalFreightHzd { get; set; }
        public Nullable<decimal> TotalAdminCharges { get; set; }
        public Nullable<decimal> TotalChargesDue { get; set; }
        public Nullable<int> TotalShipSameDay { get; set; }
        public Nullable<int> TotalShipNextDay { get; set; }
        public Nullable<int> TotalShipSecondDay { get; set; }
        public Nullable<int> TotalShipOther { get; set; }
        public Nullable<decimal> ChargeGrandTotal { get; set; }
        public Nullable<decimal> ChargeManualEntry { get; set; }
        public Nullable<decimal> ChargeManualEntryRevenue { get; set; }
        public Nullable<decimal> ChargeFollowUp { get; set; }
        public Nullable<decimal> ChargeProductSetup { get; set; }
        public Nullable<decimal> ChargeProductMaintenance { get; set; }
        public Nullable<decimal> ChargeLabelSetup { get; set; }
        public Nullable<decimal> ChargeLabelPrint { get; set; }
        public Nullable<decimal> ChargeRelabel { get; set; }
        public Nullable<decimal> ChargeRelabelLabor { get; set; }
        public Nullable<decimal> ChargeMsdsCoaPrint { get; set; }
        public Nullable<decimal> ChargeCCProcessFee { get; set; }
        public Nullable<decimal> ChargeRushShipment { get; set; }
        public Nullable<decimal> ChargeEmptyContainer { get; set; }
        public Nullable<decimal> ChargeEmptyPail { get; set; }
        public Nullable<decimal> ChargeInactiveStockStorage { get; set; }
        public Nullable<decimal> ChargeITProjectSupport { get; set; }
        public Nullable<decimal> CreditCC { get; set; }
        public Nullable<decimal> ChargeGlobalProcessing { get; set; }
        public Nullable<decimal> ChargeEmptyDrum { get; set; }
        public Nullable<decimal> ChargePailsFreight { get; set; }
    }
}
