//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientAccountRep
    {
        public int AccountRepID { get; set; }
        public int ClientID { get; set; }
        public string AccountRepUserID { get; set; }
        public string AccountRepName { get; set; }
        public string AccountRepEmail { get; set; }
    }
}
