//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int ClientID { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public Nullable<int> GlobalClientID { get; set; }
        public string ClientCode { get; set; }
        public string ClientName { get; set; }
        public string CMCLocation { get; set; }
        public string CustomerReference { get; set; }
        public string CMCLongCustomer { get; set; }
        public string ClientCurrency { get; set; }
        public string ClientUM { get; set; }
        public string ClientNetTerm { get; set; }
        public Nullable<bool> MSDS { get; set; }
        public Nullable<bool> TDS { get; set; }
        public Nullable<bool> COA { get; set; }
        public string DocumentDirectory { get; set; }
        public string MSDS_Folder { get; set; }
        public string TDS_Folder { get; set; }
        public string COA_Folder { get; set; }
        public string SP_ServiceSummary { get; set; }
        public string SP_Detail1 { get; set; }
        public string SP_Detail2 { get; set; }
        public string SP_Detail3 { get; set; }
        public string SP_Detail4 { get; set; }
        public string SP_Detail5 { get; set; }
        public Nullable<System.DateTime> SP_RevDate { get; set; }
        public string SP_CommValue { get; set; }
        public string SP_COARequired { get; set; }
        public string SP_TDSRequired { get; set; }
        public string SP_MSDSLanguage { get; set; }
        public string SP_Freezable { get; set; }
        public string SP_LabelLanguage { get; set; }
        public string SP_Expedite { get; set; }
        public string BOLComment { get; set; }
        public string LogoFileName { get; set; }
        public string ClientReference { get; set; }
        public string ClientEntityName { get; set; }
        public string MSDSFileDir { get; set; }
        public string TDSFileDir { get; set; }
        public string COAFileDir { get; set; }
        public string LogoFileDir { get; set; }
        public string InvoiceAddress { get; set; }
        public string InvoiceEmailTo { get; set; }
        public string KeyContactDir { get; set; }
        public string ClientContact { get; set; }
        public string CMCContact { get; set; }
        public string ClientUrl { get; set; }
        public string ProductSetupDetails { get; set; }
        public string SDSLanguage { get; set; }
        public string SDSUpdateMethod { get; set; }
        public string LabelLanguage { get; set; }
        public Nullable<bool> SDSRequired { get; set; }
        public Nullable<bool> COARequired { get; set; }
        public Nullable<bool> TDSRequired { get; set; }
        public Nullable<bool> StdCoverLetterRequired { get; set; }
        public string SpecialReqAllowed { get; set; }
        public string InventoryReports { get; set; }
        public string CeaseShipPeriod { get; set; }
        public string ReplenishmentLeadDays { get; set; }
        public Nullable<bool> ExpDateOnLabel { get; set; }
        public string ExpDateRules { get; set; }
        public string WasteProcedure { get; set; }
        public string InventoryBusinessRules { get; set; }
        public string CommercialInvoiceValue { get; set; }
        public string FreezableProcedure { get; set; }
        public Nullable<bool> SurveyUsed { get; set; }
        public string CSBusinessRules { get; set; }
        public string ShippingRules { get; set; }
        public string ShipConfirmEmail { get; set; }
        public string DelayConfirmEmail { get; set; }
        public string OrderConfirmEmail { get; set; }
        public string InvoiceSegregation { get; set; }
        public string ChargesSummary { get; set; }
        public string PartialDeliveryAllowed { get; set; }
        public string ClientStatus { get; set; }
        public Nullable<bool> ActiveProfile { get; set; }
        public Nullable<System.DateTimeOffset> ActiveDate { get; set; }
        public Nullable<int> SurchageHazard { get; set; }
        public Nullable<int> SurchargeFlammable { get; set; }
        public Nullable<int> SurchargeHeat { get; set; }
        public Nullable<int> SurchargeRefrigerate { get; set; }
        public Nullable<int> SurchargeFreeze { get; set; }
        public Nullable<int> SurchargeClean { get; set; }
        public Nullable<int> SurchargeNalgene { get; set; }
        public Nullable<int> SurchargeNitrogen { get; set; }
        public Nullable<int> SurchargeBiocide { get; set; }
        public Nullable<int> SurchargeBlend { get; set; }
        public Nullable<int> SurchargeKosher { get; set; }
        public Nullable<int> HazDHServLvl1 { get; set; }
        public Nullable<int> HazDHServLvl2 { get; set; }
        public Nullable<int> HazDHServLvl3 { get; set; }
        public Nullable<int> HazDHServLvl4 { get; set; }
        public Nullable<int> NonHazDHServLvl1 { get; set; }
        public Nullable<int> NonHazDHServLvl2 { get; set; }
        public Nullable<int> NonHazDHServLvl3 { get; set; }
        public Nullable<int> NonHazDHServLvl4 { get; set; }
        public string MDB_CMCBE { get; set; }
        public byte[] LogoFile { get; set; }
        public Nullable<int> CSRNumber { get; set; }
        public string CSRName { get; set; }
        public string IC { get; set; }
    }
}
