//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDhRate
    {
        public int DhRateID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string HazNonHaz { get; set; }
        public Nullable<decimal> DhServiceLevel1 { get; set; }
        public Nullable<decimal> DhServiceLevel2 { get; set; }
        public Nullable<decimal> DhServiceLevel3 { get; set; }
        public Nullable<decimal> DhServiceLevel4 { get; set; }
        public string Customerreference_MDB { get; set; }
        public string Location_MDB { get; set; }
    }
}
