//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGHS
    {
        public int GHSID { get; set; }
        public int ProductDetailID { get; set; }
        public string SignalWord { get; set; }
        public string Symbol1 { get; set; }
        public string Symbol2 { get; set; }
        public string Symbol3 { get; set; }
        public string Symbol4 { get; set; }
        public string Symbol5 { get; set; }
        public string OtherLabelInfo { get; set; }
    }
}
