//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvTrans
    {
        public int InvTransID { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> BulkID { get; set; }
        public Nullable<int> StockID { get; set; }
        public Nullable<int> TransQty { get; set; }
        public Nullable<decimal> TransAmount { get; set; }
        public Nullable<int> UserID { get; set; }
        public string TransNotes { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string LogRecordStatus_MDB { get; set; }
        public string Company_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string ProductCode_MDB { get; set; }
        public string LotNumber_MDB { get; set; }
        public string Size_MDB { get; set; }
    }
}
