//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string BillingGroup { get; set; }
        public string WarehouseLocation { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> VerifyDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTimeOffset> InvoiceDate { get; set; }
        public string InvoicePeriod { get; set; }
        public string PeriodMonth { get; set; }
        public Nullable<int> PeriodYear { get; set; }
        public string PONumber { get; set; }
        public string NetTerm { get; set; }
        public string BillTo { get; set; }
        public string RemitTo { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Tier { get; set; }
        public string OrderType { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SampleShipSameDay { get; set; }
        public Nullable<int> SampleShipNextDay { get; set; }
        public Nullable<int> SampleShipSecondDay { get; set; }
        public Nullable<int> SampleShipOther { get; set; }
        public Nullable<int> TotalSamples { get; set; }
        public Nullable<decimal> TotalCostSamples { get; set; }
        public Nullable<decimal> TotalFreight { get; set; }
        public Nullable<decimal> TotalFrtHzdSchg { get; set; }
        public Nullable<decimal> TotalAdminCharge { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> SamplesQty { get; set; }
        public Nullable<decimal> SamplesRate { get; set; }
        public Nullable<decimal> SamplesCharge { get; set; }
        public Nullable<int> RevenueQty { get; set; }
        public Nullable<decimal> RevenueRate { get; set; }
        public Nullable<decimal> RevenueCharge { get; set; }
        public Nullable<int> NonRevenueQty { get; set; }
        public Nullable<decimal> NonRevenueRate { get; set; }
        public Nullable<decimal> NonRevenueCharge { get; set; }
        public Nullable<int> ManualEntryQty { get; set; }
        public Nullable<decimal> ManualEntryRate { get; set; }
        public Nullable<decimal> ManualEntryCharge { get; set; }
        public Nullable<int> FollowUpQty { get; set; }
        public Nullable<decimal> FollowUpRate { get; set; }
        public Nullable<decimal> FollowUpCharge { get; set; }
        public Nullable<int> LabelPrtQty { get; set; }
        public Nullable<decimal> LabelPrtRate { get; set; }
        public Nullable<decimal> LabelPrtCharge { get; set; }
        public Nullable<int> ReLabelPrtQty { get; set; }
        public Nullable<decimal> ReLabelPrtRate { get; set; }
        public Nullable<decimal> ReLabelPrtCharge { get; set; }
        public Nullable<int> ReLabelFeeQty { get; set; }
        public Nullable<decimal> ReLabelFeeRate { get; set; }
        public Nullable<decimal> ReLabelFeeCharge { get; set; }
        public Nullable<int> ProductSetupQty { get; set; }
        public Nullable<decimal> ProductSetupRate { get; set; }
        public Nullable<decimal> ProductSetupCharge { get; set; }
        public Nullable<int> CCProcessQty { get; set; }
        public Nullable<decimal> CCProcessRate { get; set; }
        public Nullable<decimal> CCProcessCharge { get; set; }
        public Nullable<decimal> CCCredit { get; set; }
        public Nullable<decimal> GlobalProcessCharge { get; set; }
        public Nullable<decimal> MiscCreditCharge { get; set; }
        public Nullable<decimal> ITSupportCharge { get; set; }
        public Nullable<decimal> LabelStockCharge { get; set; }
        public Nullable<decimal> EmptyDrumCharge { get; set; }
        public Nullable<int> RushShipQty { get; set; }
        public Nullable<decimal> RushShipRate { get; set; }
        public Nullable<decimal> RushShipCharge { get; set; }
        public Nullable<int> EmptyPailsQty { get; set; }
        public Nullable<decimal> EmptyPailsRate { get; set; }
        public Nullable<decimal> EmptyPailsCharge { get; set; }
        public Nullable<decimal> EmptyPailsFgtCharge { get; set; }
        public Nullable<int> InactiveStockQty { get; set; }
        public Nullable<decimal> InactiveStockRate { get; set; }
        public Nullable<decimal> InactiveStockCharge { get; set; }
        public Nullable<decimal> HM181PkgCharge { get; set; }
        public Nullable<decimal> DocHandlingCharge { get; set; }
        public Nullable<decimal> MinimalSampleCharge { get; set; }
    }
}
