//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int InvoiceID { get; set; }
        public Nullable<int> InvoiceNumber { get; set; }
        public string BillingGroup { get; set; }
        public string WarehouseLocation { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ClientName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTimeOffset> UpdateDate { get; set; }
        public Nullable<bool> VerifiedAccuracy { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> VerifyDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTimeOffset> InvoiceDate { get; set; }
        public string InvoicePeriod { get; set; }
        public Nullable<System.DateTime> InvoiceStartDate { get; set; }
        public Nullable<System.DateTime> InvoiceEndDate { get; set; }
        public string PONumber { get; set; }
        public string NetTerm { get; set; }
        public string BillTo { get; set; }
        public string RemitTo { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Tier { get; set; }
        public string OrderType { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SampleShipSameDay { get; set; }
        public Nullable<int> SampleShipNextDay { get; set; }
        public Nullable<int> SampleShipSecondDay { get; set; }
        public Nullable<int> SampleShipOther { get; set; }
        public Nullable<int> TotalSamples { get; set; }
        public Nullable<decimal> TotalCostSamples { get; set; }
        public Nullable<decimal> TotalFreight { get; set; }
        public Nullable<decimal> TotalFrtHzdSchg { get; set; }
        public Nullable<decimal> TotalAdminCharge { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> SamplesQty { get; set; }
        public Nullable<decimal> SamplesRate { get; set; }
        public Nullable<decimal> SamplesCharge { get; set; }
        public Nullable<int> EmptyPackagingQuantity { get; set; }
        public Nullable<decimal> EmptyPackagingRate { get; set; }
        public Nullable<decimal> EmptyPackagingCharge { get; set; }
        public Nullable<int> HandlingQuantity { get; set; }
        public Nullable<decimal> HandlingRate { get; set; }
        public Nullable<decimal> HandlingCharge { get; set; }
        public Nullable<int> InactiveProductsQuantity { get; set; }
        public Nullable<decimal> InactiveProductsRate { get; set; }
        public Nullable<decimal> InactiveProductsCharge { get; set; }
        public Nullable<int> ProductSetupChangesQuantity { get; set; }
        public Nullable<decimal> ProductSetupChangesRate { get; set; }
        public Nullable<decimal> ProductSetupChangesCharge { get; set; }
        public Nullable<int> MiscellaneousLaborQuantity { get; set; }
        public Nullable<decimal> MiscellaneousLaborRate { get; set; }
        public Nullable<decimal> MiscellaneousLaborCharge { get; set; }
        public Nullable<int> FollowUpOrderQuantity { get; set; }
        public Nullable<decimal> FollowUpOrderRate { get; set; }
        public Nullable<decimal> FollowUpOrderCharge { get; set; }
        public Nullable<int> RefrigeratorStorageQuantity { get; set; }
        public Nullable<decimal> RefrigeratorStorageRate { get; set; }
        public Nullable<decimal> RefrigeratorStorageCharge { get; set; }
        public Nullable<int> GHSLabelsQuantity { get; set; }
        public Nullable<decimal> GHSLabelsRate { get; set; }
        public Nullable<decimal> GHSLabelsCharge { get; set; }
        public Nullable<int> ITFeeQuantity { get; set; }
        public Nullable<decimal> ITFeeRate { get; set; }
        public Nullable<decimal> ITFeeCharge { get; set; }
        public Nullable<int> LabelsPrintedQuantity { get; set; }
        public Nullable<decimal> LabelsPrintedRate { get; set; }
        public Nullable<decimal> LabelsPrintedCharge { get; set; }
        public Nullable<int> LaborRelabelQuantity { get; set; }
        public Nullable<decimal> LaborRelabelRate { get; set; }
        public Nullable<decimal> LaborRelabelCharge { get; set; }
        public Nullable<int> LiteratureQuantity { get; set; }
        public Nullable<decimal> LiteratureRate { get; set; }
        public Nullable<decimal> LiteratureCharge { get; set; }
        public Nullable<int> LabelStockQuantity { get; set; }
        public Nullable<decimal> LabelStockRate { get; set; }
        public Nullable<decimal> LabelStockCharge { get; set; }
        public Nullable<int> LabelMaintainanceQuantity { get; set; }
        public Nullable<decimal> LabelMaintainanceRate { get; set; }
        public Nullable<decimal> LabelMaintainanceCharge { get; set; }
        public Nullable<int> MSDSPrintsQuantity { get; set; }
        public Nullable<decimal> MSDSPrintsRate { get; set; }
        public Nullable<decimal> MSDSPrintsCharge { get; set; }
        public Nullable<int> NewLabelSetupQuantity { get; set; }
        public Nullable<decimal> NewLabelSetupRate { get; set; }
        public Nullable<decimal> NewLabelSetupCharge { get; set; }
        public Nullable<int> NewProductSetupQuantity { get; set; }
        public Nullable<decimal> NewProductSetupRate { get; set; }
        public Nullable<decimal> NewProductSetupCharge { get; set; }
        public Nullable<int> OtherQuantity { get; set; }
        public Nullable<decimal> OtherRate { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<int> PalletReturnQuantity { get; set; }
        public Nullable<decimal> PalletReturnRate { get; set; }
        public Nullable<decimal> PalletReturnCharge { get; set; }
        public Nullable<int> QCStorageQuantity { get; set; }
        public Nullable<decimal> QCStorageRate { get; set; }
        public Nullable<decimal> QCStorageCharge { get; set; }
        public Nullable<int> RelabelsQuantity { get; set; }
        public Nullable<decimal> RelabelsRate { get; set; }
        public Nullable<decimal> RelabelsCharge { get; set; }
        public Nullable<int> WarehouseStorageQuantity { get; set; }
        public Nullable<decimal> WarehouseStorageRate { get; set; }
        public Nullable<decimal> WarehouseStorageCharge { get; set; }
        public Nullable<int> WHMISLabelsQuantity { get; set; }
        public Nullable<decimal> WHMISLabelsRate { get; set; }
        public Nullable<decimal> WHMISLabelsCharge { get; set; }
        public Nullable<int> WasteProcessingQuantity { get; set; }
        public Nullable<decimal> WasteProcessingRate { get; set; }
        public Nullable<decimal> WasteProcessingCharge { get; set; }
    }
}
