//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvLogType
    {
        public int ID { get; set; }
        public string LogType { get; set; }
        public string LogTypeDescription { get; set; }
        public string LogType_Legacy { get; set; }
    }
}
