//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderTrans
    {
        public int OrderTransID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> OrderItemID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public string TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> TransQty { get; set; }
        public Nullable<decimal> TransAmount { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<int> CMCOrder_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string BusinessUnit_MDB { get; set; }
        public string ChargeSource_MDB { get; set; }
        public string Company_MDB { get; set; }
        public string Location_MDB { get; set; }
        public string CustomerReference_MDB { get; set; }
    }
}
