//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderImport
    {
        public int ImportID { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string CMCOrderID { get; set; }
        public string ClientID { get; set; }
        public string ClientName { get; set; }
        public string Division { get; set; }
        public string Territory { get; set; }
        public string CMCWarehouse { get; set; }
        public string OrderType { get; set; }
        public string OrderDate { get; set; }
        public string ApprovalDate { get; set; }
        public string DeliveryDate { get; set; }
        public string ClientOrderID { get; set; }
        public string CustOrderID { get; set; }
        public string CompanyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string RegionLocated { get; set; }
        public string ShipExpedite { get; set; }
        public string ShipAcctNum { get; set; }
        public string ACode { get; set; }
        public string Carrier { get; set; }
        public string Market { get; set; }
        public string EndUse { get; set; }
        public string Comments { get; set; }
        public string ApplicationTypes { get; set; }
        public string DecisionTimeFrame { get; set; }
        public string DecisionRole { get; set; }
        public string DecisionSupport { get; set; }
        public string RequestorName { get; set; }
        public string RequestorEmail { get; set; }
        public string RequestorPhone { get; set; }
        public string RequestorComments { get; set; }
        public string SalesRepName { get; set; }
        public string SalesEmail { get; set; }
        public string SalesPhone { get; set; }
        public string Distributor { get; set; }
        public string ItemID { get; set; }
        public string ItemNumber { get; set; }
        public string ItemName { get; set; }
        public string Quantity { get; set; }
        public string Size { get; set; }
        public string LotNumber { get; set; }
        public string ItemNote { get; set; }
        public string AnnualUsage { get; set; }
        public string IncludeLiterature { get; set; }
        public string IncludeCOA { get; set; }
        public string ImportFileName { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<bool> DuplicateFlag { get; set; }
    }
}
