//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPMNote
    {
        public int PMNoteID { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public string Company_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string ProductCode_MDB { get; set; }
        public Nullable<System.DateTime> NoteDate { get; set; }
        public string Comment { get; set; }
        public string Notes { get; set; }
        public string LotNumber_MDB { get; set; }
        public string Location_MDB { get; set; }
        public string MigrateStatus { get; set; }
    }
}
