//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionDetail
    {
        public int ID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> ShelfID { get; set; }
        public string UM { get; set; }
        public Nullable<decimal> Unit_Weight { get; set; }
        public Nullable<decimal> SS_REORDMIN { get; set; }
        public Nullable<decimal> SS_REORDMAX { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> AvgOfUnit_Weight { get; set; }
        public Nullable<decimal> RecQty { get; set; }
        public string Status { get; set; }
        public string ProdCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> InvRequestedQty { get; set; }
        public Nullable<int> ProdActualQty { get; set; }
        public Nullable<int> LabelQty { get; set; }
        public string SpecialInstructions { get; set; }
        public string ShelfStockLocation { get; set; }
        public string PackagePartNumber { get; set; }
    }
}
