//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPreferredCarrierList
    {
        public int ID { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<bool> CommInvoiceReq { get; set; }
        public string NonHaz_Sm { get; set; }
        public string NonHaz_Lg { get; set; }
        public string NonHaz_IncoTerms { get; set; }
        public string HazIATA_Sm { get; set; }
        public string HazIATA_Lg { get; set; }
        public string HazGround_LQ { get; set; }
        public string HazGround { get; set; }
        public string Haz_Incoterms { get; set; }
        public string Incoterms_Alt { get; set; }
        public string Notes_General { get; set; }
        public string Notes_IATA_ADR { get; set; }
        public string NonHazIncoterms_Alt { get; set; }
        public string HazIncoterms_Alt { get; set; }
    }
}
