//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductXRef
    {
        public int ProductXRefID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string CMCProductCode { get; set; }
        public string CMCSize { get; set; }
        public string CustProductCode { get; set; }
        public string CustProductName { get; set; }
        public string CustSize { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string Company_MDB { get; set; }
        public string Location_MDB { get; set; }
    }
}
