//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductDetail
    {
        public int ProductDetailID { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public Nullable<int> SGLegacyID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string BusArea { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CustCode { get; set; }
        public Nullable<bool> MultiLotReq { get; set; }
        public Nullable<bool> ExtendableExpDt { get; set; }
        public string HarmonizedCode { get; set; }
        public string EndUse { get; set; }
        public Nullable<System.DateTime> SGRevisionDate { get; set; }
        public Nullable<System.DateTime> MSDSRevisionDate { get; set; }
        public string MSDSRevisionNumber { get; set; }
        public Nullable<System.DateTime> LabelRevisionDate { get; set; }
        public string LabelNumber { get; set; }
        public Nullable<bool> ProductChecked { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedWhen { get; set; }
        public Nullable<bool> EPABiocide { get; set; }
        public string LabelInfo { get; set; }
        public Nullable<bool> GHSReady { get; set; }
        public Nullable<decimal> CustomsValue { get; set; }
        public string CustomsValueUnit { get; set; }
        public Nullable<bool> GlobalProduct { get; set; }
        public Nullable<bool> AccuracyVerified { get; set; }
        public Nullable<bool> PolmerizationHazard { get; set; }
        public string SDSContactName { get; set; }
        public string SDSContactPhone { get; set; }
        public Nullable<System.DateTime> ChinaCertificationDate { get; set; }
        public string LabelContactName { get; set; }
        public string LabelContactPhone { get; set; }
        public Nullable<bool> TechnicalSheet { get; set; }
        public Nullable<System.DateTime> TechnicalSheetRevisionDate { get; set; }
        public string EmergencyContactNumber { get; set; }
        public Nullable<bool> EPAHazardousWaste { get; set; }
        public Nullable<bool> NonRCRAWaste { get; set; }
        public string WasteProfileNumber { get; set; }
        public Nullable<System.DateTime> LastUpDate { get; set; }
        public string Company_MDB { get; set; }
        public string MasterCode_MDB { get; set; }
        public string Division_MDB { get; set; }
    }
}
