//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPriority
    {
        public int ID { get; set; }
        public Nullable<int> PriorityNumber { get; set; }
        public string PriorityColor { get; set; }
        public string ColorCode { get; set; }
        public string DayOfWeek { get; set; }
    }
}
