//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackageType
    {
        public int PackageTypeID { get; set; }
        public string PartNumber { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public string DOTSpec { get; set; }
        public string UNSpec { get; set; }
    }
}
