//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRates
    {
        public int ClientID { get; set; }
        public Nullable<decimal> RevenueRate { get; set; }
        public Nullable<decimal> NonRevenueRate { get; set; }
        public Nullable<decimal> ManualEntryRate { get; set; }
        public Nullable<decimal> FollowUpRate { get; set; }
        public Nullable<decimal> LabelPrtRate { get; set; }
        public Nullable<decimal> ReLabelPrtRate { get; set; }
        public Nullable<decimal> ReLabelFeeRate { get; set; }
        public Nullable<decimal> ProductSetupRate { get; set; }
        public Nullable<decimal> CCProcessRate { get; set; }
        public Nullable<decimal> RushShipRate { get; set; }
        public Nullable<decimal> EmptyPailsRate { get; set; }
        public Nullable<decimal> InactiveStockRate { get; set; }
        public Nullable<decimal> MinimalSampleCharge { get; set; }
    }
}
