//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReportCriteria
    {
        public int ReportCriteriaID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string ReportCategory { get; set; }
        public string Criteria { get; set; }
        public string Display { get; set; }
        public string ReportName { get; set; }
        public string QueryName { get; set; }
        public Nullable<bool> DateCriteria { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string Company_MDB { get; set; }
        public string Location_MDB { get; set; }
    }
}
