//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRates
    {
        public int RatesID { get; set; }
        public int ClientID { get; set; }
        public Nullable<decimal> EmptyPackagingRate { get; set; }
        public Nullable<decimal> HandlingRate { get; set; }
        public Nullable<decimal> InactiveProductRate { get; set; }
        public Nullable<decimal> ProductSetupChangesRate { get; set; }
        public Nullable<decimal> MiscellaneousLaborRate { get; set; }
        public Nullable<decimal> FollowUpOrderRate { get; set; }
        public Nullable<decimal> RefrigeratorStorageRate { get; set; }
        public Nullable<decimal> GHSLabelsRate { get; set; }
        public Nullable<decimal> ITFeeRate { get; set; }
        public Nullable<decimal> LabelsPrintedRate { get; set; }
        public Nullable<decimal> LaborRelabelRate { get; set; }
        public Nullable<decimal> LiteratureRate { get; set; }
        public Nullable<decimal> LabelStockRate { get; set; }
        public Nullable<decimal> LabelMaintainanceRate { get; set; }
        public Nullable<decimal> MSDSPrintsRate { get; set; }
        public Nullable<decimal> NewLabelSetupRate { get; set; }
        public Nullable<decimal> NewProductSetupRate { get; set; }
        public Nullable<decimal> OtherRate { get; set; }
        public Nullable<decimal> PalletReturnRate { get; set; }
        public Nullable<decimal> QCStorageRate { get; set; }
        public Nullable<decimal> RelabelsRate { get; set; }
        public Nullable<decimal> WarehouseStorageRate { get; set; }
        public Nullable<decimal> WHMISLabelsRate { get; set; }
        public Nullable<decimal> WasteProcessingRate { get; set; }
        public Nullable<decimal> MinimumInvoiceCharge { get; set; }
    }
}
