//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSampSize
    {
        public int SampSizeID { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string ProductCode { get; set; }
        public string Size { get; set; }
        public Nullable<bool> HazardSurcharge { get; set; }
        public Nullable<bool> FlammableSurcharge { get; set; }
        public Nullable<bool> HeatSurcharge { get; set; }
        public Nullable<bool> RefrigeratorSurcharge { get; set; }
        public Nullable<bool> FreezerSurcharge { get; set; }
        public Nullable<bool> CleanSurcharge { get; set; }
        public Nullable<bool> BlendSurcharge { get; set; }
        public Nullable<bool> NalgeneSurcharge { get; set; }
        public Nullable<bool> NitrogenSurcharge { get; set; }
        public Nullable<bool> BiocideSurcharge { get; set; }
        public Nullable<bool> KosherSurcharge { get; set; }
        public Nullable<bool> LabelSurcharge { get; set; }
        public Nullable<bool> OtherSurcharge { get; set; }
        public Nullable<decimal> OtherSurchargeAmt { get; set; }
        public string New { get; set; }
        public Nullable<bool> InactiveSize { get; set; }
        public Nullable<bool> WebOEInclude { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> LegacyID { get; set; }
        public string Company_MDB { get; set; }
        public string Location_MDB { get; set; }
    }
}
