//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShelfMaster
    {
        public int ShelfID { get; set; }
        public Nullable<int> ProductDetailID { get; set; }
        public string Warehouse { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> UnitWeight { get; set; }
        public Nullable<decimal> ReorderMin { get; set; }
        public Nullable<decimal> ReorderMax { get; set; }
        public Nullable<decimal> ReorderQty { get; set; }
        public string Bin { get; set; }
        public Nullable<bool> HazardSurcharge { get; set; }
        public Nullable<bool> FlammableSurcharge { get; set; }
        public Nullable<bool> HeatSurcharge { get; set; }
        public Nullable<bool> RefrigSurcharge { get; set; }
        public Nullable<bool> FreezerSurcharge { get; set; }
        public Nullable<bool> CleanSurcharge { get; set; }
        public Nullable<bool> BlendSurcharge { get; set; }
        public Nullable<bool> NalgeneSurcharge { get; set; }
        public Nullable<bool> NitrogenSurcharge { get; set; }
        public Nullable<bool> BiocideSurcharge { get; set; }
        public Nullable<bool> KosherSurcharge { get; set; }
        public Nullable<bool> LabelSurcharge { get; set; }
        public Nullable<bool> OtherSurcharge { get; set; }
        public Nullable<decimal> OtherSurchargeAmt { get; set; }
        public string NewItem { get; set; }
        public Nullable<bool> InactiveSize { get; set; }
        public Nullable<bool> WebOEInclude { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string PackagePartNumber_MDB { get; set; }
        public Nullable<int> PackageID { get; set; }
        public string Company_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string ProductCode_MDB { get; set; }
        public string BusArea { get; set; }
        public string Mnemonic { get; set; }
        public string GroundHazard { get; set; }
        public string AirHazard { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Discontinued { get; set; }
        public string Alert { get; set; }
        public string CustCode { get; set; }
        public string MigrationNotes { get; set; }
    }
}
