//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSQlTable
    {
        public int ID { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> FieldTypeID { get; set; }
        public string FieldType { get; set; }
        public string FieldLength { get; set; }
        public string App { get; set; }
    }
}
