//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuggestedBulk
    {
        public int id { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string SupplyID { get; set; }
        public Nullable<int> ShelfLife { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ProductMasterAge { get; set; }
        public Nullable<decimal> BulkCurrentAvailable { get; set; }
        public Nullable<decimal> ShelfCurrentAvailable { get; set; }
        public Nullable<decimal> CurrentAvailable { get; set; }
        public Nullable<decimal> BulkShippedPastYear { get; set; }
        public Nullable<decimal> BulkShippedPerDay { get; set; }
        public Nullable<decimal> ShelfShippedPastYear { get; set; }
        public Nullable<decimal> ShelfShippedPerDay { get; set; }
        public Nullable<System.DateTime> BulkLatestExpirationDate { get; set; }
        public Nullable<int> BulkDaysTilExpiration { get; set; }
        public Nullable<System.DateTime> ShelfLatestExpirationDate { get; set; }
        public Nullable<int> ShelfDaysTilExpiration { get; set; }
        public Nullable<System.DateTime> UseThisExpirationDate { get; set; }
        public Nullable<int> UseThisDaysTilExpiration { get; set; }
        public Nullable<int> DaysSupplyLeft { get; set; }
        public Nullable<int> AverageLeadTime { get; set; }
        public Nullable<bool> PrePackedBulk { get; set; }
        public Nullable<bool> ReorderThis { get; set; }
        public Nullable<bool> BulkOnOrder { get; set; }
        public Nullable<int> ReorderWeight { get; set; }
        public string ReorderNotes { get; set; }
        public Nullable<bool> IsAddOn { get; set; }
        public string SessionID { get; set; }
        public string UserName { get; set; }
    }
}
