//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipTrans
    {
        public int ShipTransID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CarrierID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string CarrierName { get; set; }
        public string Tracking { get; set; }
        public string ShipAccount { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> DimWeight { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
    }
}
