//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUN
    {
        public int UNID { get; set; }
        public string UNNumber { get; set; }
        public string HazardClass { get; set; }
        public string ProperShippingName { get; set; }
        public string NOSName { get; set; }
        public string LabelReq { get; set; }
        public string SubClass { get; set; }
        public string SubSidLabelReq { get; set; }
        public string PackingGroup { get; set; }
    }
}
