//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBulkTransForReplenishment
    {
        public int LogID { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> LogQty { get; set; }
        public Nullable<decimal> LogAmount { get; set; }
        public string BulkStatus { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
    }
}
