//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBulkLevel
    {
        public int BulkID { get; set; }
        public Nullable<int> LegacyLogID { get; set; }
        public Nullable<int> LegacyBulkStockID { get; set; }
        public string Warehouse { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public string LotNumber { get; set; }
        public string Bin { get; set; }
        public string UM { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> ReceiveWeight { get; set; }
        public Nullable<decimal> CurrentWeight { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public string BulkStatus { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> QCDate { get; set; }
        public Nullable<bool> PackOut { get; set; }
        public string ReturnLocation { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public string ContainerColor { get; set; }
        public Nullable<System.DateTime> CeaseShipDate { get; set; }
        public string ContainerNotes { get; set; }
        public string BulkLabelNote { get; set; }
        public string ReceivedBy { get; set; }
        public string EnteredBy { get; set; }
        public string Carrier { get; set; }
        public string LogNotes { get; set; }
        public string ContainerType { get; set; }
        public Nullable<bool> COAIncluded { get; set; }
        public Nullable<bool> MSDSIncluded { get; set; }
        public Nullable<int> PercentSolids { get; set; }
        public Nullable<int> NCO { get; set; }
        public Nullable<decimal> TEW { get; set; }
        public Nullable<int> PercentOH { get; set; }
        public string LogRecordStatus { get; set; }
        public string ReceivedAsCode { get; set; }
        public string ReceivedAsName { get; set; }
        public Nullable<bool> flammable { get; set; }
        public Nullable<bool> freezer { get; set; }
        public Nullable<bool> refrigerator { get; set; }
        public string OtherStorage { get; set; }
        public Nullable<bool> RestrictedQty { get; set; }
        public Nullable<decimal> RestrictedAmt { get; set; }
        public Nullable<bool> MarkedForReturn { get; set; }
        public string Company_MDB { get; set; }
        public string Division_MDB { get; set; }
        public string MasterCode_MDB { get; set; }
        public string ProductName_MDB { get; set; }
        public string Location_MDB { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public string MigrationNotes { get; set; }
        public int ProductDetailID { get; set; }
    }
}
