//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPhoenix.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShelfTransForReplenishment
    {
        public string TransType { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> TransQty { get; set; }
        public Nullable<decimal> TransAmount { get; set; }
        public Nullable<int> ProductMasterID { get; set; }
        public string Status { get; set; }
        public int InvTransID { get; set; }
    }
}
