using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MvcPhoenix.Models
{
    public class ProductMaster
    {
        public string logofilename { get; set; }
        public int productmasterid { get; set; }
        public int? clientid { get; set; }
        public string clientname { get; set; }
        public int? masterdivisionid { get; set; }
        public bool? discontinued { get; set; }
        public string mastercode { get; set; }
        public string mastername { get; set; }
        public int? shelflife { get; set; }
        public decimal? density { get; set; }
        public decimal? restrictedamount { get; set; }
        public int? sglegacyid { get; set; }
        public int? sdlegacyid { get; set; }
        public string supplyid { get; set; }
        public bool? noreorder { get; set; }
        public bool? packoutonreceipt { get; set; }
        public decimal? restrictedtoamount { get; set; }
        public DateTime? createdate { get; set; }
        public string masternotes { get; set; }
        public bool? masternotesalert { get; set; }
        public int? reorderadjustmentdays { get; set; }
        public int? ceaseshipdifferential { get; set; }
        public bool? cleanroomgmp { get; set; }
        public bool? nitrogenblanket { get; set; }
        public bool? moisturesensitive { get; set; }
        public bool? mixwell { get; set; }
        public string mixinginstructions { get; set; }
        public bool? refrigerate { get; set; }
        public bool? donotpackabove60 { get; set; }
        public string handlingother { get; set; }
        public bool? flammableground { get; set; }
        public bool? heatpriortofilling { get; set; }
        public decimal? flashpoint { get; set; }
        public string heatinginstructions { get; set; }
        public string other { get; set; }
        public string normalappearence { get; set; }
        public string rejectioncriterion { get; set; }
        public bool? hood { get; set; }
        public bool? labhood { get; set; }
        public bool? walkinhood { get; set; }
        public bool? safetyglasses { get; set; }
        public bool? gloves { get; set; }
        public string glovetype { get; set; }
        public bool? apron { get; set; }
        public bool? armsleeves { get; set; }
        public bool? respirator { get; set; }
        public bool? faceshield { get; set; }
        public bool? fullsuit { get; set; }
        public bool? cleanroomequipment { get; set; }
        public bool? otherequipment { get; set; }
        public bool? toxic { get; set; }
        public bool? highlytoxic { get; set; }
        public bool? reproductivetoxin { get; set; }
        public bool? corrosivehaz { get; set; }
        public bool? sensitizer { get; set; }
        public bool? carcinogen { get; set; }
        public bool? ingestion { get; set; }
        public bool? inhalation { get; set; }
        public bool? skin { get; set; }
        public bool? skincontact { get; set; }
        public bool? eyecontact { get; set; }
        public bool? combustible { get; set; }
        public bool? corrosive { get; set; }
        public bool? flammable { get; set; }
        public bool? oxidizer { get; set; }
        public bool? reactive { get; set; }
        public bool? hepatotoxins { get; set; }
        public bool? nephrotoxins { get; set; }
        public bool? neurotoxins { get; set; }
        public bool? hepatopoetics { get; set; }
        public bool? pulmonarydisfunction { get; set; }
        public bool? reporductivetoxin { get; set; }
        public bool? cutaneoushazards { get; set; }
        public bool? eyehazards { get; set; }
        public string health { get; set; }
        public string flammability { get; set; }
        public string reactivity { get; set; }
        public string otherequipmentdescription { get; set; }
        public bool? booties { get; set; }
        public string hazardclassground_sg { get; set; }
        public bool? irritant { get; set; }
        public bool? righttoknow { get; set; }
        public bool? sara { get; set; }
        public bool? flammablestorageroom { get; set; }
        public bool? firelist { get; set; }
        public bool? freezablelist { get; set; }
        public bool? refrigeratedlist { get; set; }
        public string msdsothernumber { get; set; }
        public bool? freezerstorage { get; set; }
        public bool? clientreq { get; set; }
        public bool? cmcreq { get; set; }
        public string returnlocation { get; set; }
        public bool? specialblend { get; set; }
        public bool? sara302ehs { get; set; }
        public bool? sara313 { get; set; }
        public bool? halfmaskrespirator { get; set; }
        public bool? fullfacerespirator { get; set; }
        public bool? torque { get; set; }
        public string torquerequirements { get; set; }
        public string otherstorage { get; set; }
        public string eecall { get; set; }
        public string rphrasesall { get; set; }
        public string sphrasesall { get; set; }
        public string phall { get; set; }
        public string english { get; set; }
        public string german { get; set; }
        public string dutch { get; set; }
        public string eecsymbol1 { get; set; }
        public string eecsymbol2 { get; set; }
        public string eecsymbol3 { get; set; }
        public string handling { get; set; }
        public string shippingnotes { get; set; }
        public string otherlabelnotes { get; set; }
        public string productdescription { get; set; }
        public bool? peroxideformer { get; set; }
        public string grnshipname { get; set; }
        public string grnshipnamed { get; set; }
        public string grnosname { get; set; }
        public string grnunnumber { get; set; }
        public string grnhazcl { get; set; }
        public string grnpkgrp { get; set; }
        public string grnlabel { get; set; }
        public string grnsublabel { get; set; }
        public string grntremacard { get; set; }
        public string airshipname { get; set; }
        public string airnosname { get; set; }
        public string airunnumber { get; set; }
        public string airhazcl { get; set; }
        public string airpkgrp { get; set; }
        public string airlabel { get; set; }
        public string airsublabel { get; set; }
        public string airhazsubcl { get; set; }
        public string grnhazsubcl { get; set; }
        public string seashipname { get; set; }
        public string seashipnamed { get; set; }
        public string seanosname { get; set; }
        public string seaunnum { get; set; }
        public string seapkgrp { get; set; }
        public string seahazcl { get; set; }
        public string sealabel { get; set; }
        public string seahazsubcl { get; set; }
        public string seasublabel { get; set; }
        public string seahazmat { get; set; }
        public string seaemsno { get; set; }
        public string seamfagno { get; set; }
    }
}